version: "3"

x-aws-logs_retention: 14
x-aws-loadbalancer: arn:aws:elasticloadbalancing:us-east-1:8888888:loadbalancer/app/CariAiWeb/777777777

services:

  sonarqube:
    #build:
    #  context: ./
    image: docker.io/lbolanos/sonarqube:v7
    #image: 8888888.dkr.ecr.us-east-1.amazonaws.com/sonarqube-dev
    container_name: sonarqube
    #command: /bin/sh -c 'if [ $$(sysctl vm.max_map_count | cut -f2 -d=) -lt 262144 ]; then sysctl -w vm.max_map_count=262144; fi'
    #command: /bin/sh -c 'cat /etc/sysctl.conf'
    depends_on:
      - db
    ports:
      - target: 9000
        x-aws-protocol: http
    networks:
      - sonarnet
    environment:
      - S1ONAR_JDBC_URL=jdbc:postgresql://db/sonar
      - S1ONAR_JDBC_USERNAME=sonar
      - S1ONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      #- ./sysctl.conf:/etc/sysctl.conf:ro
      #- sonarqube_data:/opt/sonarqube/extensions
      #- sonarqube_data:/opt/sonarqube/lib/bundled-plugins
      #- sonarqube_data:/opt/sonarqube/conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
    privileged: true
  db:
    image: postgres:latest
    container_name: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data

#x-aws-cloudformation:
#  Resources:
#    Sonarqube9000Listener:
#      Properties:
#        Certificates:
#          - CertificateArn: arn:aws:acm:us-east-1:8888888:certificate/f59bb330-c9f4-473c-b060-dc4d3636a839
#        Protocol: HTTPS
#        Port: 9000

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data:
    driver_opts:
      performance-mode: maxIO
      throughput-mode: bursting
      uid: 0
      gid: 0
  sonarqube_logs:
    driver_opts:
      performance-mode: maxIO
      throughput-mode: bursting
      uid: 0
      gid: 0
  postgresql_data:

